<a href="https://colab.research.google.com/github/denverkim/BA_FALL2026/blob/main/BA26_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# replace 투토리얼
https://queirozf.com/entries/pandas-dataframe-replace-examples

In [1]:
import pandas as pd

df = pd.DataFrame({
    'name':['john','mary','paul'],
    'age':[30,25,40],
    'city':['new york','los angeles','london']
})
df

   name  age         city
0  john   30     new york
1  mary   25  los angeles
2  paul   40       london

In [2]:
df.replace([25],40)

   name  age         city
0  john   30     new york
1  mary   40  los angeles
2  paul   40       london

In [3]:
import pandas as pd

df = pd.DataFrame({
    'name':['john','mary','paul'],
    'age':[30,25,40],
    'city':['new york','los angeles','london']
})
df

   name  age         city
0  john   30     new york
1  mary   25  los angeles
2  paul   40       london

In [4]:
df.replace({
    25:26,
    'john':'johnny'
})

     name  age         city
0  johnny   30     new york
1    mary   26  los angeles
2    paul   40       london

In [6]:
import pandas as pd

df = pd.DataFrame({
    'name':['john','mary','paul'],
    'age':[30,25,40],
    'city':['new york','los angeles','london']
})
df

   name  age         city
0  john   30     new york
1  mary   25  los angeles
2  paul   40       london

In [7]:
df.replace('jo.+','FOO',regex=True)

   name  age         city
0   FOO   30     new york
1  mary   25  los angeles
2  paul   40       london

In [8]:
df = pd.DataFrame({
    'name':['john','mary','paul'],
    'num_children':[0,4,5],
    'num_pets':[0,1,2]
})
df

   name  num_children  num_pets
0  john             0         0
1  mary             4         1
2  paul             5         2

In [9]:
# replace 0 with 1 in column "num_pets" only!
df.replace({'num_pets':{0:1}})

   name  num_children  num_pets
0  john             0         1
1  mary             4         1
2  paul             5         2

# 인코딩 투토리얼
https://contactsunny.medium.com/label-encoder-vs-one-hot-encoder-in-machine-learning-3fc273365621

In [33]:
data = {
        'country':['france', 'spain', 'germany', 'spain', 'germany', 'france', 'spain', 'france', 'germany', 'france'],
              'age':[44, 27, 30, 38, 40, 35,66, 48, 50, 37],

        'salary':[72000, 48000, 54000, 61000, 55000, 58000, 52000, 79000, 83000, 67000],
        'purchased':['no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'no', 'yes']
        }
df = pd.DataFrame(data)
df

   country  age  salary purchased
0   france   44   72000        no
1    spain   27   48000       yes
2  germany   30   54000        no
3    spain   38   61000        no
4  germany   40   55000       yes
5   france   35   58000       yes
6    spain   66   52000        no
7   france   48   79000       yes
8  germany   50   83000        no
9   france   37   67000       yes

In [34]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df.country = le.fit_transform(df.country)
df

   country  age  salary purchased
0        0   44   72000        no
1        2   27   48000       yes
2        1   30   54000        no
3        2   38   61000        no
4        1   40   55000       yes
5        0   35   58000       yes
6        2   66   52000        no
7        0   48   79000       yes
8        1   50   83000        no
9        0   37   67000       yes

In [35]:
le.classes_ #범주 확인할 때

array(['france', 'germany', 'spain'], dtype=object)

In [36]:
#get_dummy
dummy = pd.get_dummies(df.purchased)
dummy

      no    yes
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True
5  False   True
6   True  False
7  False   True
8   True  False
9  False   True

In [37]:
df = pd.concat([df, dummy], axis=1)
df

   country  age  salary purchased     no    yes
0        0   44   72000        no   True  False
1        2   27   48000       yes  False   True
2        1   30   54000        no   True  False
3        2   38   61000        no   True  False
4        1   40   55000       yes  False   True
5        0   35   58000       yes  False   True
6        2   66   52000        no   True  False
7        0   48   79000       yes  False   True
8        1   50   83000        no   True  False
9        0   37   67000       yes  False   True

In [38]:
df = df.drop(['no', 'purchased'], axis=1)
df

   country  age  salary    yes
0        0   44   72000  False
1        2   27   48000   True
2        1   30   54000  False
3        2   38   61000  False
4        1   40   55000   True
5        0   35   58000   True
6        2   66   52000  False
7        0   48   79000   True
8        1   50   83000  False
9        0   37   67000   True

In [39]:
df.rename(columns={'yes':'purchased'}, inplace=True)
df

   country  age  salary  purchased
0        0   44   72000      False
1        2   27   48000       True
2        1   30   54000      False
3        2   38   61000      False
4        1   40   55000       True
5        0   35   58000       True
6        2   66   52000      False
7        0   48   79000       True
8        1   50   83000      False
9        0   37   67000       True

In [43]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
dummy = ohe.fit_transform(df[['country', 'purchased']]).toarray()
dummy_df = pd.DataFrame(dummy, columns=['france', 'germany', 'spain', 'no', 'yes'])
dummy_df

   france  germany  spain   no  yes
0     1.0      0.0    0.0  1.0  0.0
1     0.0      0.0    1.0  0.0  1.0
2     0.0      1.0    0.0  1.0  0.0
3     0.0      0.0    1.0  1.0  0.0
4     0.0      1.0    0.0  0.0  1.0
5     1.0      0.0    0.0  0.0  1.0
6     0.0      0.0    1.0  1.0  0.0
7     1.0      0.0    0.0  0.0  1.0
8     0.0      1.0    0.0  1.0  0.0
9     1.0      0.0    0.0  0.0  1.0

In [44]:
df = pd.concat([df, dummy_df], axis=1)
df

   country  age  salary  purchased  france  germany  spain   no  yes
0        0   44   72000      False     1.0      0.0    0.0  1.0  0.0
1        2   27   48000       True     0.0      0.0    1.0  0.0  1.0
2        1   30   54000      False     0.0      1.0    0.0  1.0  0.0
3        2   38   61000      False     0.0      0.0    1.0  1.0  0.0
4        1   40   55000       True     0.0      1.0    0.0  0.0  1.0
5        0   35   58000       True     1.0      0.0    0.0  0.0  1.0
6        2   66   52000      False     0.0      0.0    1.0  1.0  0.0
7        0   48   79000       True     1.0      0.0    0.0  0.0  1.0
8        1   50   83000      False     0.0      1.0    0.0  1.0  0.0
9        0   37   67000       True     1.0      0.0    0.0  0.0  1.0

# 세일 데이터 전처리 실습

In [45]:
# 훈련, 테스트 데이터를 임포트한 후에 기본 데이터 탐색 수행

import pandas as pd

train = pd.read_csv('/content/bigmart_train.csv')
train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [46]:
# 데이터 사이즈 확인
train.shape

(8523, 12)

In [47]:
# 데이터 타입 확인
train.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

In [48]:
# 기초 통계량
train.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [49]:
# 널값 검색
train.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [51]:
# 테스트 테이터에 아웃렛세일 열을 만들고 1을 할당
test = pd.read_csv('/content/bigmart_test.csv')
test['Item_Outlet_Sales'] = 1
test

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1,1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1,1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store,1
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1,1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,1
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,1

In [54]:
# Combine train and test data. 훈련과 테스트 데이터를 합침
df = pd.concat([train, test])
df.shape

(14204, 12)

In [56]:
# 분실값 및 매칭되지 않는 값 대체
# 1. 아이템 무게의 분실값을 중위수로 대체
df['Item_Weight'].fillna(df['Item_Weight'].median(), inplace=True)

/tmp/ipykernel_671/2459201569.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Item_Weight'].fillna(df['Item_Weight'].median(), inplace=True)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.50,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,1.0000
5677,FDD47,7.60,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,1.0000
5678,NCO17,10.00,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,1.0000
5679,FDJ26,15.30,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,1.0000
5680,FDU37,9.50,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,1.0000

In [57]:
# 널값 확인
df.isna().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [63]:
# Impute missing values by median for item visibility. 노출도 0인 값을 중위수로 대체
df.loc[df['Item_Visibility']==0, 'Item_Visibility'] = df.Item_Visibility.median()

In [64]:
df.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,14204.000000,14204.000000,14204.000000,14204.000000,14204.000000
mean,12.759739,0.069296,141.004977,1997.830681,1309.265447
std,4.234851,0.048749,62.086938,8.371664,1699.483470
min,4.555000,0.003575,31.290000,1985.000000,1.000000
25%,9.300000,0.033143,94.012000,1987.000000,1.000000
50%,12.600000,0.054023,142.247000,1999.000000,559.272000
75%,16.000000,0.094037,185.855600,2004.000000,2163.184200
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [69]:
# 아웃렛 사이즈 빈도
df['Outlet_Size'].value_counts(dropna=False)

Outlet_Size
Medium    4655
Other     4016
Small     3980
High      1553
Name: count, dtype: int64

In [67]:
# 아웃렛 사이즈의 분실값을 Other로 대체
df.Outlet_Size.fillna('Other', inplace=True)

In [68]:
# 아웃렛 사이즈 빈도 체크
df.Outlet_Size.value_counts()

Outlet_Size
Medium    4655
Other     4016
Small     3980
High      1553
Name: count, dtype: int64

In [70]:
# 지방 함유율 빈도
df['Item_Fat_Content'].value_counts()

Item_Fat_Content
Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: count, dtype: int64

In [72]:
# 지방함유율의 값 대체
# LF to Low Fat, reg to Regular, low fat to Low Fat
df['Item_Fat_Content'] = df['Item_Fat_Content'].replace(['LF', 'low fat'], 'Low Fat')
df['Item_Fat_Content'] = df['Item_Fat_Content'].replace('reg', 'Regular')

In [73]:
# 바꿨는지 확인
df.Item_Fat_Content.value_counts()

Item_Fat_Content
Low Fat    9185
Regular    5019
Name: count, dtype: int64

In [74]:
# Year라는 새로운 열 만들기
df['Year'] = 2026 - df['Outlet_Establishment_Year']
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Year
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,27
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,17
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,27
3,FDX07,19.20,Regular,0.054021,Fruits and Vegetables,182.0950,OUT010,1998,Other,Tier 3,Grocery Store,732.3800,28
4,NCD19,8.93,Low Fat,0.054021,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,39

In [77]:
# 필요없는 열을 삭제 (exclude item identifier, outlet identifier, item fat content, outlet establishment year, and item type).
df.drop(['Item_Identifier', 'Outlet_Identifier', 'Item_Fat_Content', 'Outlet_Establishment_Year', 'Item_Type'], axis=1, inplace=True)
df.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Year
0,9.30,0.016047,249.8092,Medium,Tier 1,Supermarket Type1,3735.1380,27
1,5.92,0.019278,48.2692,Medium,Tier 3,Supermarket Type2,443.4228,17
2,17.50,0.016760,141.6180,Medium,Tier 1,Supermarket Type1,2097.2700,27
3,19.20,0.054021,182.0950,Other,Tier 3,Grocery Store,732.3800,28
4,8.93,0.054021,53.8614,High,Tier 3,Supermarket Type1,994.7052,39

In [78]:
# 범주형 변수를 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Outlet_Size'] = le.fit_transform(df['Outlet_Size'])
df['Outlet_Location_Type'] = le.fit_transform(df['Outlet_Location_Type'])
df['Outlet_Type'] = le.fit_transform(df['Outlet_Type'])
df.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Year
0,9.30,0.016047,249.8092,1,0,1,3735.1380,27
1,5.92,0.019278,48.2692,1,2,2,443.4228,17
2,17.50,0.016760,141.6180,1,0,1,2097.2700,27
3,19.20,0.054021,182.0950,2,2,0,732.3800,28
4,8.93,0.054021,53.8614,0,2,1,994.7052,39